name: Latest blog post workflow
on: 
    schedule:
        - cron: '0 * * * *'
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4
            - uses: gautamkrishnar/blog-post-workflow@v1
              with: 
                max_post_count: "10"
                feed_list: "https://hashnode.com/@esl1h/rss.xml,https://medium.com/feed/@esl1h,https://stackoverflow.com/feeds/user/4122311,https://esli.blog.br/rss.xml"
